import * as env from 'dotenv-safe';

const {
  MONGO_HOSTNAME,
  MONGO_USERNAME,
  MONGO_PASSWORD,
  MONGO_PORT,
  MONGO_DB_NAME,
  JWT_SECRET,
} = process.env;

// const MONGO_CONNECTION_URL = `mongodb://${MONGO_HOSTNAME}:${MONGO_PORT}/${MONGO_DB_NAME}`;
const MONGO_CONNECTION_URL = `mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOSTNAME}/test?retryWrites=true&w=majority`;


export {
  MONGO_HOSTNAME,
  MONGO_USERNAME,
  MONGO_PASSWORD,
  MONGO_PORT,
  MONGO_DB_NAME,
  MONGO_CONNECTION_URL,
  JWT_SECRET,
}
